In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
data = [[1, 'Alice'], [2, 'Bob'], [3, 'Charlie']]
df = pd.DataFrame(data, columns=['ID','Name'])
print(df)

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [ ]:
df2 = pd.read_csv('data.csv')

In [ ]:
print(df2)

   name   age   score
0   Kim    27      92
1   Lee    33      98
2  Park    19      87

In [ ]:
df3 = pd.read_csv('train.csv')

In [ ]:
print(df3)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [ ]:
url = 'https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv'
df4 = pd.read_csv(url, delimiter='\t')
print(df4)

           gameId   creationTime  gameDuration  seasonId  winner  firstBlood  \
0      3326086514  1504279457970          1949         9       1           2
1      3229566029  1497848803862          1851         9       1           1
2      3327363504  1504360103310          1493         9       1           2
3      3326856598  1504348503996          1758         9       1           1
4      3330080762  1504554410899          2094         9       1           2
...           ...            ...           ...       ...     ...         ...
51485  3308904636  1503076540231          1944         9       2           1
51486  3215685759  1496957179355          3304         9       2           1
51487  3322765040  1504029863961          2156         9       2           2
51488  3256675373  1499562036246          1475         9       2           2
51489  3317333020  1503612754059          1445         9       1           1

       firstTower  firstInhibitor  firstBaron  firstDragon  ...  \
0               1               1           1            1  ...
1               1               1           0            1  ...
2               1               1           1            2  ...
3               1               1           1            1  ...
4               1               1           1            1  ...
...           ...             ...         ...          ...  ...
51485           2               2           0            2  ...
51486           1               2           2            2  ...
51487           2               2           0            1  ...
51488           2               2           0            2  ...
51489           1               1           1            2  ...

       t2_towerKills  t2_inhibitorKills  t2_baronKills  t2_dragonKills  \
0                  5                  0              0               1
1                  2                  0              0               0
2                  2                  0              0               1
3                  0                  0              0               0
4                  3                  0              0               1
...              ...                ...            ...             ...
51485             10                  2              0               4
51486             11                  7              4               4
51487             10                  2              0               2
51488             11                  3              0               1
51489              1                  0              0               1

       t2_riftHeraldKills  t2_ban1  t2_ban2  t2_ban3  t2_ban4  t2_ban5
0                       1      114       67       43       16       51
1                       0       11       67      238       51      420
2                       0      157      238      121       57       28
3                       0      164       18      141       40       51
4                       0       86       11      201      122       18
...                   ...      ...      ...      ...      ...      ...
51485                   0       55       -1       90      238      157
51486                   1      157       55      119      154      105
51487                   0      113      122       53       11      157
51488                   0      154       39       51       90      114
51489                   0       11      157      141       31       18

[51490 rows x 61 columns]

In [ ]:
df5 = pd.read_excel('BoxOffice.xlsx', index_col=0)
print(df5)

            영화명        개봉일           매출액       관객수  스크린수    상영횟수 대표국적     국적  \
순위
1            명량 2014-07-30  135758208810  17615844  1587  188724   한국     한국
2          극한직업 2019-01-23  139655543516  16266338  2003  292816   한국     한국
3     신과함께-죄와 벌 2017-12-20  115727528087  14414658  1912  214631   한국     한국
4          국제시장 2014-12-17  110945002730  14264059  1044  212698   한국     한국
5    어벤져스: 엔드게임 2019-04-24  122492181020  13977602  2835  246433   미국     미국
..          ...        ...           ...       ...   ...     ...  ...    ...
196         스파이 2013-09-05   24513098305   3436092   785   72805   한국  한국,태국
197   그것만이 내 세상 2018-01-17   27457704382   3420287   956   95444   한국     한국
198    토이 스토리 4 2019-06-20   28763352540   3400623  1336   85913   미국     미국
199           돈 2019-03-20   28870244062   3389125  1431  120809   한국     한국
200    맨 인 블랙 3 2012-05-24   27301520070   3379762   770   69538   미국     미국

                     배급사
순위
1              (주)씨제이이엔엠
2              (주)씨제이이엔엠
3          롯데쇼핑㈜롯데엔터테인먼트
4              (주)씨제이이엔엠
5     월트디즈니컴퍼니코리아 유한책임회사
..                   ...
196            (주)씨제이이엔엠
197            (주)씨제이이엔엠
198   월트디즈니컴퍼니코리아 유한책임회사
199               (주)쇼박스
200  한국소니픽쳐스릴리징브에나비스타영화㈜

[200 rows x 9 columns]

In [ ]:
df6 = pd.read_excel('data.xlsx')

df6.head(3)

    반   이름 성별    국어    수학 응시여부 확인여부
0  A반  구이서  남  90.0  89.0   응시   확인
1  B반  김이정  여  78.0  45.0   응시   확인
2  A반  오지수  남   NaN   NaN   응시   확인

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   반       10 non-null     object
 1   이름      10 non-null     object
 2   성별      10 non-null     object
 3   국어      7 non-null      float64
 4   수학      7 non-null      float64
 5   응시여부    8 non-null      object
 6   확인여부    7 non-null      object
dtypes: float64(2), object(5)
memory usage: 688.0+ bytes

In [ ]:
df6.반

0    A반
1    B반
2    A반
3    B반
4    A반
5    A반
6    B반
7    B반
8    A반
9    B반
Name: 반, dtype: object

In [ ]:
df6['반']

0    A반
1    B반
2    A반
3    B반
4    A반
5    A반
6    B반
7    B반
8    A반
9    B반
Name: 반, dtype: object

In [ ]:
df반이름 = df6[['반', '이름']]
df반이름

    반   이름
0  A반  구이서
1  B반  김이정
2  A반  오지수
3  B반  김선후
4  A반  하진희
5  A반  강현진
6  B반  김진솔
7  B반  박서준
8  A반  김성희
9  B반  이지서

In [ ]:
res = df6[df6['국어'] > 80]

In [ ]:
df6.sort_values(by=['국어'], ascending = False)

    반   이름 성별    국어     수학 응시여부 확인여부
0  A반  구이서  남  90.0   89.0   응시   확인
6  B반  김진솔  남  90.0   89.0   응시   확인
9  B반  이지서  여  86.0  100.0   응시   확인
1  B반  김이정  여  78.0   45.0   응시   확인
7  B반  박서준  여  78.0   45.0   응시   확인
3  B반  김선후  남  33.0   44.0   응시  NaN
4  A반  하진희  여   0.0   85.0   응시  NaN
2  A반  오지수  남   NaN    NaN   응시   확인
5  A반  강현진  남   NaN    NaN  NaN  NaN
8  A반  김성희  남   NaN    NaN  NaN   확인

In [ ]:
value_counts = df6['성별'].value_counts()
value_counts

성별
남    6
여    4
Name: count, dtype: int64

In [ ]:
# 데이터를 이용하여 데이터프레임을 생성하세요.

df7 = pd.DataFrame({'학생':['John', 'Alice', 'Bob', 'Emily'],
                   '수학':[90,87,78,92],
                   '영어':[85,91,80,88],
                   '과학':[88,89,85,82]})
df7

      학생  수학  영어  과학
0   John  90  85  88
1  Alice  87  91  89
2    Bob  78  80  85
3  Emily  92  88  82

In [ ]:
# 생성한 데이터프레임의 요약 통계 정보를 출력하세요.

df_describe = df7.describe()
df_describe

              수학         영어         과학
count   4.000000   4.000000   4.000000
mean   86.750000  86.000000  86.000000
std     6.184658   4.690416   3.162278
min    78.000000  80.000000  82.000000
25%    84.750000  83.750000  84.250000
50%    88.500000  86.500000  86.500000
75%    90.500000  88.750000  88.250000
max    92.000000  91.000000  89.000000

In [ ]:
# 생성한 데이터프레임에서 '수학' 점수가 가장 높은 학생의 정보를 출력하세요.

df7[df7['수학'] == df7['수학'].max()]

      학생  수학  영어  과학
3  Emily  92  88  82

In [ ]:
# 생성한 데이터프레임에서 '수학' 점수가 90점 이상인 학생의 정보를 출력하세요.

math_90 = df7[df7['수학'] >= 90]
math_90

      학생  수학  영어  과학
0   John  90  85  88
3  Emily  92  88  82

In [ ]:
# 역대 박스오피스 파일을 데이터프레임으로 생성하기

# 1. 데이터 파일을 생성한 후 데이터프레임의 정보를 출력하시오.

df8 = pd.read_excel('BoxOffice.xlsx')
df8

,순위,영화명,개봉일,매출액,관객수,스크린수,상영횟수,대표국적,국적,배급사
0,1,명량,2014-07-30,135758208810,17615844,1587,188724,한국,한국,(주)씨제이이엔엠
1,2,극한직업,2019-01-23,139655543516,16266338,2003,292816,한국,한국,(주)씨제이이엔엠
2,3,신과함께-죄와 벌,2017-12-20,115727528087,14414658,1912,214631,한국,한국,롯데쇼핑㈜롯데엔터테인먼트
3,4,국제시장,2014-12-17,110945002730,14264059,1044,212698,한국,한국,(주)씨제이이엔엠
4,5,어벤져스: 엔드게임,2019-04-24,122492181020,13977602,2835,246433,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
...,...,...,...,...,...,...,...,...,...,...
195,196,스파이,2013-09-05,24513098305,3436092,785,72805,한국,"한국,태국",(주)씨제이이엔엠
196,197,그것만이 내 세상,2018-01-17,27457704382,3420287,956,95444,한국,한국,(주)씨제이이엔엠
197,198,토이 스토리 4,2019-06-20,28763352540,3400623,1336,85913,미국,미국,월트디즈니컴퍼니코리아 유한책임회사
198,199,돈,2019-03-20,28870244062,3389125,1431,120809,한국,한국,(주)쇼박스
199,200,맨 인 블랙 3,2012-05-24,27301520070,3379762,770,69538,미국,미국,한국소니픽쳐스릴리징브에나비스타영화㈜

In [ ]:
# 대표국적별 영화 편수를 집계하시오

nation = df8['대표국적'].value_counts()
nation

대표국적
한국    116
미국     82
일본      1
영국      1
Name: count, dtype: int64

In [ ]:
# 대표국적이 '영국'인 데이터를 출력하시오

df8[df8['대표국적']=='영국']

,순위,영화명,개봉일,매출액,관객수,스크린수,상영횟수,대표국적,국적,배급사
194,195,어바웃 타임,2013-12-05,25312684300,3449451,568,67267,영국,영국,유니버설픽쳐스인터내셔널 코리아(유)

In [ ]:
# 대표국적별 최상위 순위를 출력하시오

grouped_min = df8.groupby('대표국적')['순위'].min()
print(grouped_min)

대표국적
미국      5
영국    195
일본    172
한국      1
Name: 순위, dtype: int64